version: "3"

services:
  seata:
    restart: always
    image: seataio/seata-server
    hostname: seata.dev
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
    networks:
      dev:
        aliases:
          - seata.dev
networks:
  dev:
    external:
      name: dev
