version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-server
    env_file:
      - .env
    volumes:
      - ./.data/logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    container_name: nacos-mysql
    build:
      context: .
      dockerfile: Dockerfile
    image: local/nacos-mysql:latest
    env_file:
      - .env
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
