version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq.dev
    image: rabbitmq:3-management
    networks:
      dev:
        aliases:
          - rabbitmq.dev
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always
volumes:
  rabbitmq:
    external: true
networks:
  dev:
    external: true
    name: dev
