version: "3"
services:
  dev_mariadb:
    container_name: dev_mariadb
    hostname: mariadb.dev
    image: mariadb:latest
    restart: always
    networks:
      dev:
        aliases:
          - mariadb.dev
    ports:
      - 3326:3306/tcp
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: dev
    volumes:
      - ./log:/var/log/mysql:rw
      - ./conf.d:/etc/mysql/mariadb.conf.d:rw
      - mariadb:/var/lib/mysql
volumes:
  mariadb:
    external: true
networks:
  dev:
    external:
      name: dev
