version: '3.7'
services:
  mysql:
    image: mysql:8.0.32
    pull_policy: if_not_present
    restart: always
    volumes:
      - .data/mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
    expose:
      - "3306"
    ports:
      - "${DB_PORT:-3306}:3306"
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION
      --lower_case_table_names=2
    healthcheck:
      test: "mysql ${MYSQL_DATABASE} -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} -e 'SELECT 1;'"
      interval: 5s
      timeout: 5s
      start_period: 30s
      retries: 60