# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.disksize.size = '40GB'
  config.vm.network "private_network", ip: "172.16.16.66"
  config.vm.provider "virtualbox" do |vb|
      vb.name = "vm-ubuntu"
      vb.memory = "2048"
      vb.cpus = 1
  end
end
