# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.disksize.size = '40GB'
  config.vm.network "private_network", ip: "172.16.16.66"
  config.vm.provider "virtualbox" do |vb|
      vb.name = "vm-ubuntu"
      vb.memory = "2048"
      vb.cpus = 1
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://172.16.16.1:1087/"
    config.proxy.https    = "http://172.16.16.1:1087/"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end
  # config.vm.synced_folder "/Users/ray/Code", "/Users/home/vagrant/Code", type: "nfs"
end
