version: "3.8"
services:
  redis:
    image: redis:alpine
    pull_policy: if_not_present
    restart: always
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
      ]
    expose:
      - "6379"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./.data/redis:/data
